### ISSUE TITLE
Shader problems since new update

### ISSUE THREAD

**Issue by TheKillerey** [moonshadow565/ritobin#2]
It looks like that Riot made changes to the bin indirectly. Converting etc. works with the tool but it is causing issues when using it.
I already tested only the .mapgeo without modified .bin and the mesh seems to look normal.
![League of Legends Screenshot 2021 03 20 - 11 12 34 45](https://user-images.githubusercontent.com/18242778/111866394-71494580-896d-11eb-817f-3641b0c9cf84.png)

**Comment by moonshadow565** [comment]
??? Closed for being inactive.
